version: '3'
services:
  bio:
    image: rayyounghong/bio:latest
    container_name: bio
    volumes:
      - ./workspace:/workspace
      - ./.jupyter:/root/.jupyter
    working_dir: /workspace
    ports:
      - "9875:9875/tcp"
    restart: always
